In [1]:
import gym

In [2]:
Game = 'FrozenLake-v0'
env = gym.make(Game)

Reset the game to the starting point

In [3]:
env.reset()

0

Visualize your current state

In [4]:
env.render()


SFFF
FHFH
FFFH
HFFG


Number of states and actions

In [5]:
print(env.observation_space.n)
print(env.action_space.n)

16
4


Take an action<br />
Action indices: LEFT = 0, DOWN = 1, RIGHT = 2, UP = 3<br />
You'll get a result in a tuple of (next_state, reward, terminal (whether the next state is a terminal state), transition probability)

In [278]:
action = 1
out = env.step(action)
out

(12, 0, True, {'prob': 1.0})

In [7]:
env.render()

  (Down)
SFFF
FHFH
FFFH
HFFG


In [283]:
model.P[5]

{0: [(1.0, 5, 0, True)],
 1: [(1.0, 5, 0, True)],
 2: [(1.0, 5, 0, True)],
 3: [(1.0, 5, 0, True)]}

In [281]:
print(env.env)

<FrozenLakeEnv<FrozenLake-v0>>


In [279]:
help(env)

Help on TimeLimit in module gym.wrappers.time_limit object:

class TimeLimit(gym.core.Wrapper)
 |  The main OpenAI Gym class. It encapsulates an environment with
 |  arbitrary behind-the-scenes dynamics. An environment can be
 |  partially or fully observed.
 |  
 |  The main API methods that users of this class need to know are:
 |  
 |      step
 |      reset
 |      render
 |      close
 |      seed
 |  
 |  And set the following attributes:
 |  
 |      action_space: The Space object corresponding to valid actions
 |      observation_space: The Space object corresponding to valid observations
 |      reward_range: A tuple corresponding to the min and max possible rewards
 |  
 |  Note: a default reward range set to [-inf,+inf] already exists. Set it if you want a narrower range.
 |  
 |  The methods are accessed publicly as "step", "reset", etc.. The
 |  non-underscored versions are wrapper methods to which we may add
 |  functionality over time.
 |  
 |  Method resolution order:
 

Acquire model stats

In [8]:
model = env.env

In [9]:
model.nS

16

In [17]:
import numpy as np

In [25]:
abs(np.zeros(model.nS)-b)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
b=np.zeros(model.nS)+1

In [24]:
range()

1.0

In [10]:
model.nA

4

In [302]:
model.P[12][2]

[(1.0, 12, 0, True)]

In [304]:
init=np.zeros(10)

In [310]:
init.argmin()

0

In [ ]:
from 

In [307]:
init.argmax()

0

All transitions after taking an action. model.P is organized as {state: {action: \[(p, state', r, terminal), ...\], ...}, ...}

In [27]:
model.P[0].keys()

dict_keys([0, 1, 2, 3])

In [46]:
q=np.random.rand(10,4)

In [118]:
q

array([[0.96508709, 0.55037931, 0.36018568, 0.91737733],
       [0.01959408, 0.46398841, 0.79397239, 0.35212296],
       [0.47391432, 0.57850056, 0.02819353, 0.2202273 ],
       [0.61556073, 0.54455082, 0.00746971, 0.35297529],
       [0.45002026, 0.7152924 , 0.49550476, 0.60835452],
       [0.52133059, 0.81693824, 0.55019568, 0.54454917],
       [0.40381453, 0.3107441 , 0.87840247, 0.1243447 ],
       [0.90243866, 0.81109759, 0.55606752, 0.99680612],
       [0.3640897 , 0.82743762, 0.45217613, 0.21123766],
       [0.19438341, 0.91742321, 0.15193755, 0.91558097]])

In [120]:
q[0]

array([0.96508709, 0.55037931, 0.36018568, 0.91737733])

In [119]:
from RLalgs.utils import epsilon_greedy

RLalgs is a package containing Reinforcement Learning algorithms Epsilon-Greedy, Policy Iteration, Value Iteration, Q-Learning, and SARSA.


In [324]:
new_q = np.zeros((10,4))

In [370]:
epsilon_greedy(np.array([123,1,2]),e=0.4)

AssertionError: 

In [360]:
epsilon_greedy(q[0],e=0.5)

0

In [72]:
action=np.argmax(q,1)

In [71]:
action

array([0, 2, 1, 0, 1, 1, 2, 3, 1, 1], dtype=int64)

In [111]:
print(model.P[4][3])

[(0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 0, 0.0, False), (0.3333333333333333, 4, 0.0, False)]


In [98]:
thisarray = np.array(model.P[1][1])

In [106]:
thisarray.shape[0]

3

In [104]:
np.random.choice(thisarray[:,1],p=thisarray[:,0])

5.0

In [69]:
np.zeros((10,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
model.P[0][0]

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 4, 0.0, False)]

Take a look at a specific state action pair

In [12]:
state0, action0 = 0, 0
model.P[state0][action0]

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 4, 0.0, False)]

In [16]:
sum([p*r+s for p,s,r,_ in model.P[0][0]])

4.0

In [13]:
model.isd

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In case you need to initialize the first state randomly.

In [14]:
#isd refers to initial state distribution
model.isd = [1 / model.nS] * model.nS
print(model.isd)

[0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625]


In [15]:
s = env.reset()
print(s)

12


End